name: 'rs-clippy-check'
description: 'Run clippy and annotate the diff with errors and warnings'
author: 'clechasseur'
inputs:
  toolchain:
    description: Toolchain to use (without the `+` sign, ex. `nightly`)
    required: false
  args:
    description: Arguments for the cargo clippy command
    required: false
  working-directory:
    description: Directory where to perform cargo clippy command
    required: false
  tool:
    description: Tool to use instead of cargo ([`cross`, `cargo-hack`])
    required: false
  cache-key:
    description: Cache key used when using a non-cargo tool
    default: rs-clippy-check
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: paperclip
  color: black
